-- =====================================================
-- SIRT 022 - PROFIL / HAK AKSES PENGGUNA
-- Tanpa NIK dan tanpa No. KK
-- =====================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text,
  user_id text unique,
  role text not null default 'warga',
  wilayah text,
  password_wajib_ganti boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint profiles_role_check
    check (role in ('admin','rt','humas','warga'))
);

-- Aktifkan RLS
alter table public.profiles enable row level security;

-- User hanya boleh melihat profil dirinya sendiri
drop policy if exists "profiles_select_own" on public.profiles;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

-- User boleh memperbarui profil dirinya sendiri
drop policy if exists "profiles_update_own" on public.profiles;

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- =====================================================
-- DAFTAR WILAYAH SIRT 022
-- =====================================================

create table if not exists public.wilayah_rt022 (
  id bigint generated by default as identity primary key,
  kode text unique not null,
  nama_gang text not null,
  blok text not null,
  aktif boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.wilayah_rt022 enable row level security;

drop policy if exists "wilayah_read_authenticated"
on public.wilayah_rt022;

create policy "wilayah_read_authenticated"
on public.wilayah_rt022
for select
to authenticated
using (aktif = true);

-- =====================================================
-- MASUKKAN WILAYAH BLOK G
-- =====================================================

insert into public.wilayah_rt022 (kode,nama_gang,blok)
values
('G1G2','Gang Family','G'),
('G2G3','Gang Cemara','G'),
('G3G4','Gang Gathotkaca','G'),
('G4G5','Gang 45','G')
on conflict (kode) do update
set nama_gang = excluded.nama_gang,
    blok = excluded.blok;

-- =====================================================
-- MASUKKAN WILAYAH BLOK H
-- =====================================================

insert into public.wilayah_rt022 (kode,nama_gang,blok)
values
('G1H1','Helios','H'),
('H1H2','Gang Ceria','H'),
('H2H3','Gang Iqro''','H'),
('H3H4','Gang Pelangi','H'),
('H4H5','Gang Pemuda','H'),
('H5H6','Gang Bhineka','H'),
('H6','Gang Danau','H')
on conflict (kode) do update
set nama_gang = excluded.nama_gang,
    blok = excluded.blok;
